### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by quicoto** [quicoto/workout-app#23]
Find a combination for HEADINGs and BODY texts in Google Fonts.

## Implementation

Don't forget to use `&display=swap` if it is not already added to the link href

**Comment by quicoto** [comment]
Montserrrat + Lato ?

**Comment by rogercornet** [comment]
Headlines: 
Montserrat Extra-Bold
https://fonts.google.com/specimen/Montserrat

Text:
Lato Regular
https://fonts.google.com/specimen/Lato
